- name: Web server automation
  hosts: web
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - nginx
          - git
        state: present

    - name: Ensure nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Clone repository
      git:
        repo: "https://github.com/ikeshav26/IaC_infra.git"
        dest: /var/www/app
        force: yes
        version: main

    - name: Deploy static file to nginx root
      copy:
        src: /var/www/app/static/index.html
        dest: /var/www/html/index.html
        remote_src: yes

    - name: Install certbot packages
      apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: present

    - name: Check if SSL already exists
      stat:
        path: /etc/letsencrypt/live/infra.ikeshav.in/fullchain.pem
      register: ssl_cert

    - name: Run certbot (only if SSL not exists)
      command: >
        certbot --nginx -d {{ domain_name }}
        --non-interactive --agree-tos
        -m {{ certbot_email }}
      when: not ssl_cert.stat.exists